#\u5404\u53c2\u6570\u7c7b\u578b\uff0csy_code\u4e2d\u6dfb\u52a0\uff0c\u8fd9\u91cc\u6dfb\u52a0\u5bf9\u5e94\u7684\u53ef\u4ee5\u52a0\u7c7b\u578b
report.parameter.type.text = <input type="text" name="@" id="@"   value=""/>
report.parameter.type.job_tp =<ait:SelectEmpTypeCode name="@" id="@" limit="#" type=""/>
report.parameter.type.job_tp_gr=<ait:SelectEmpTypeCode name="@" id="@" limit="#" type="group"/>
report.parameter.type.dept_multi=<ait:deptTreeMulti id="DEPTNO_Multi" name="@" limit="#" level2=""/>
report.parameter.type.prod_tp=<ait:SelectSyCodeByCpnyID id="@" name="@" parentNo="211424" cnpyID="${CPNY_ID}" limit="all"/>
report.parameter.type.date=<input type\="text" id\="@" name\="@" class\="date required"  format\="yyyy-MM-dd" readonly\="true" /><a class\="inputDateButton" href\="javascript\:;"><spring\:message code\="public.title.choose"/><\!-- \u9009\u62e9 --></a>
report.parameter.type.code=<ait:SelectSyCodeByCpnyID id="@" name="@" parentNo="" cnpyID="${CPNY_ID}" limit="all"/>
report.parameter.type.org=<ait:deptList name="@" cpnyId="${CPNY_ID}" id="@" limit="#"  /> <ait:deptTreeIcon	name="@" cpnyId="${CPNY_ID}" id="@" limit="#" />
report.parameter.type.branch=<ait:deptList name="@" cpnyId="${CPNY_ID}" id="@" limit="#" /><ait:deptTreeIcon name="@" cpnyId="${CPNY_ID}" id="@" limit="#"/>
report.parameter.type.emp=<input\u00a0name\="EMPNO"\u00a0value\=""\u00a0readonly\u00a0type\="hidden"\u00a0class\="input_textfield"\u00a0id\="EMPNO"\u00a0size\="10"><input\u00a0name\="EMP_NM"\u00a0value\=""\u00a0type\="text"\u00a0class\="input_textfield"\u00a0id\="EMP_NM"\u00a0size\="18"\u00a0required><a\u00a0href\="javascript\:showEmployeeSelectWindow('/sys.retrieveEmployeeList.laf?ORG_ID\='+form.ORG_ID.value)">\u00a0</a>
report.parameter.type.item=<ait\:SelectArItem   name\="@" parentNo\="all" \t limit\="all"/>
report.parameter.type.emp_owend=<ait:selectCodeMulti id="@"  name="@" parentNo="14015585"/>
report.parameter.type.emp_off=<ait:selectCodeMulti id="@"  name="@" parentNo="15118"/>    
report.parameter.type.pay_schedule=<ait:SelectPayScheduleNo name="@" id="@"/>

report.parameter.type.yyyymm=<ait\:date\u00a0 />
#\u539f\u6837\u8f93\u51fa\u7684\u53c2\u6570#
report.parameter.type.yuanyangcanshu=CPNY,PAY_CD,EMPLOYEE_OWNED,POST_FAMILY_Multi
#\u6309\u7167\u56fa\u5b9a\u683c\u5f0f\u7684\u53c2\u6570\u6761\u4ef6
report.parameter.type.gudingcanshu=CPNY_ID,PERSON_ID,CPNY
CPNY_ID.ENDESC=CPNY_ID
CPNY_ID.CNDESC=\u6cd5\u4eba
CPNY_ID.SQLTP=text
CPNY_ID.SQLTPDESC=<input type='text' name='CPNY_ID' id='CPNY_ID' readonly  value='${CPNY_ID}'/>
CPNY_ID.SOCTCD=0
PERSON_ID.ENDESC=PERSON_ID
PERSON_ID.CNDESC=\u4eba\u5458ID
PERSON_ID.SQLTP=text
PERSON_ID.SQLTPDESC=<input type="text" name="PERSON_ID" readonly id="PERSON_ID"  value="${LoginUser.personId}"/>
PERSON_ID.SOCTCD=0
CPNY.ENDESC=CPNY
CPNY.CNDESC=\u6cd5\u4eba
CPNY.SQLTP=text
CPNY.SQLTPDESC=<input type="text" name="CPNY" readonly id="CPNY"  value='${CPNY_ID}'/>
CPNY.SOCTCD=0
#\u4e0d\u540c\u670d\u52a1\u5668\u7684jsp\u9875\u9762\u8f93\u51fa\u8def\u5f84
sql.param.jsp.folderWin=\\view\\disc\\sqlparam\\
sql.param.jsp.folderUnix=/view/disc/sqlparam/
branch=<ait:SelectState id="@" name="@" parentNo="" type="BRANCH" limit="all" />
#\u53d6\u5230\u5148\u6267\u884c\u5b58\u50a8\uff0c\u8fd4\u56desql\u8bed\u53e5\u7684\u62a5\u8868\u5e8f\u53f7
report.parameter.type.zhixingcunchu=187

