#\u662f\u5426\u53d1\u9001\u90ae\u4ef6\u6807\u793a \uff08 1\uff1a\u53d1\u9001   0\uff1a\u4e0d\u53d1\u9001  \uff09
mail.send.flag=0

#\u662f\u5426\u9a8c\u8bc1
mail.smtp.auth=true

#\u4f20\u8f93\u534f\u8bae
mail.transport.protocol=smtp

#\u90ae\u4ef6\u670d\u52a1\u5668\u5730\u5740
smtp.server=smtp.sina.com

#\u90ae\u4ef6\u670d\u52a1\u5668\u9a8c\u8bc1\u7528\u6237\u540d
#tsto_sst_chrs techwin.chr
mail.username=tsto_sst_chrs

#\u90ae\u4ef6\u670d\u52a1\u5668\u9a8c\u8bc1\u5bc6\u7801
#wei19900114 tsto09
mail.password=wei19900114

#\u53d1\u4ef6\u4eba\u5730\u5740tsto_sst_chrs@sina.com
#yangkyu@ci.eagleoffice.co.kr techwin.chr@hanwha.com dung.do@ci.eagleoffice.co.kr
mail.from=techwin.chr@hanwha.com

#\u90ae\u4ef6\u63a5\u6536\u4eba  peng.xing@ci.eagleoffice.co.kr
#dung.do@ci.eagleoffice.co.kr
mail.to=lipeng@ait.net.cn

#\u5355\u70b9\u767b\u5f55url  http://10.42.200.56:9100/
mail.login.host=10.44.7.19:8088

#web service url  http://ci.eagleoffice.co.kr:80/api/services/MailService
#webservice.url=http://hanwha.eagleoffice.co.kr/api/services/MailService
#webservice.url=http://ep.circle.hanwha.com/api/axis/services/MailService
webservice.url=https://ep.cleverse.hanwha.com/soap/mail/axis/services/MailService